name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build & Push BACKEND
    - name: Build & Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./crud-dd-task-mean-app/backend
        push: true
        tags: |
          swarup98/backend-app:latest

    # 4. Build & Push FRONTEND
    - name: Build & Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./crud-dd-task-mean-app/frontend
        push: true
        tags: |
          swarup98/frontend-app:latest

    # 5. Deploy to EC2 using SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/project/crud-dd-task-mean-app
          git pull origin main
          docker-compose pull
          docker-compose up -d --build
